services:

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: stats
    ports:
      - "5433:5432"

  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ewm
    ports:
      - "5432:5432"

  ewm-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: ewm-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345
      STATS_SERVER_URL: http://stats-server:9090
    ports:
      - "8080:8080"

