services:
  # сервис статистики
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345

  # база сервиса статистики
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345

  # основной сервис
  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090
    depends_on:
      ewm-db:
        condition: service_healthy

  # база основного сервиса
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345